### ISSUE TITLE
New mangle format?

### ISSUE THREAD

**Issue by RenniePet** [mattgallagher/CwlDemangle#5]
Just a heads-up: There's been a fair amount of activity on Demangle.cpp since December, and talk of "new mangling". Maybe preparation for Swift 4?

Sigh. I was just about to integrate your great Swift-based demangle code into my Swift logging module, now I fear that could soon be a wasted investment.

(But I still think it's marvelous that you did this work.)

**Comment by mattgallagher** [comment]
I've already ported this code from Swift 2 to Swift 3. I will absolutely update CwlDemangle once Swift 4 hits beta - it's not really worth worrying about until then since it anything could potentially change.

In general though, it's some very specific edge cases that are changing (archetypes, etc) not common cases. The real reason for the new mangling format is to be "ABI stable". They're going to ensure that it stops changing so much from version to version. That's actually going to make this project much *easier*.

**Comment by RenniePet** [comment]
Thanks for replying, and thanks again for creating this project. I'll reconsider incorporating it into my logging module.

**Comment by RenniePet** [comment]
Matt, just in case you're interested, I have now incorporated your demangler into my iOS logging module, and it works like a charm. Thank you very much for creating this and publishing it.

My only "problem" was that, being an iPhone / Swift newbie, and not being at all interested in developing for Mac, I would have liked to first re-target your project for the iPhone simulator so I could run main.swift as a test app, just to get a bit familiar with the usage of the code. But my attempts to re-target your project just didn't work, presumably due to my lack of knowledge. So in the end I just copied the source code over to my logging library module project, and was able to get your main.swift code running on the iPhone simulator in that way. Is it possible and simple to publish a project that will work for both iOS and Mac?  

Thanks again. Also for the very well-written and informative article that goes with this project.

**Comment by kabiroberai** [comment]
Since Swift 4 is now officially out, could the repo be updated to support the new format? (Sorry if this is considered thread hijacking – if it is, I can create a new issue)

**Comment by mattgallagher** [comment]
I've reopened this issue. Yes, I'll update this library soon.

**Comment by klaas** [comment]
Would love to see it for Swift 4 as well!

@mattgallagher, loving Cwl for ages! 😍

**Comment by rlaferla** [comment]
Please update for Swift 4.  The current class doesn't compile.  Can't find SwiftName.

**Comment by mattgallagher** [comment]
Fully updated for Swift 4. All test cases in the latest manglings.txt file parse correctly.

Added the full set of Print options too, so you can choose to display different options.

The interface has changed slightly. See the first function in main.swift for a usage example or the four functions at the top of CwlDemangle.swift for API documentation.

**Comment by klaas** [comment]
Thank you very much!

**Comment by uber-mahyar2** [comment]
Sorry to hijack again, it looks like some changes have happened with swift 4.1+:

```
Swift Demangling Error: Unexpected character at position 27 in "_T07RxSwift10Disposable_pWc0_"
Swift Demangling Error: Unexpected character at position 23 in "_T08Realtime7SessionVWs"
Swift Demangling Error: Unexpected character at position 15 in "_T07RxSwiftytWb92_"
Swift Demangling Error: Unexpected character at position 38 in "_T07RxSwift3BagVyAA10Disposable_pGSgWc0_"
Swift Demangling Error: Unexpected character at position 7 in "_T0SqWy.17"
Swift Demangling Error: Unexpected character at position 15 in "_T07RxSwiftytWc252_"
Swift Demangling Error: Unexpected character at position 7 in "_T0SqWy"
Swift Demangling Error: Unexpected character at position 5 in "_T0Ta"
```

I'm guessing we would wait until xcode 10 / swift 5 is fully released?  From a test run of about 30'000 symbols, only a dozen come up as invalid.  So it looks like there aren't many changes.

Thanks for making this, it really helps me in extracting module names in a consistent manner!
