### ISSUE TITLE
CWLDemangle sometimes inserts U+0001 characters in print()

### ISSUE THREAD

**Issue by uber-mahyar2** [mattgallagher/CwlDemangle#8]
For example this symbol:

"_T0s14StringProtocolP10FoundationSS5IndexVADRtzrlE10componentsSaySSGqd__11separatedBy_tsAARd__lF"

demangles into this when you call SwiftSymbol.print() on it:

"(extension in Foundation):Swift.StringProtocol<>.components(separatedBy: A\u{1}) -> Swift.Array<Swift.String>"

If you just dump this string as part of a json serialization process, then it will be invalid json and cannot be parsed by other json deserializers.

In swift you would represent the U+0001 char as "\u{1}".   You can see a list of unicode characters here: https://en.wikipedia.org/wiki/List_of_Unicode_characters

**Comment by mattgallagher** [comment]
This bug doesn't occur in the current version (was probably an issue with unresolved symbolic references). I've included a test (`testUnicodeProblem`) to confirm.
